### ISSUE TITLE
Change the way of variables in window.h file.

### ISSUE THREAD

**Issue by Zi-han-Huang** [Mario-el-khoury/Smart-Intonation#10]
Give real meaning for each variable in window.h not just say "the initialization of XXX" when writing comment. The person who make documents will do that rather than changing the code before pull request to the main code, in order to avoid conflict.

**Comment by Mario-el-khoury** [comment]
The comments in the window.h file are present to generate a Doxygen documentation, the exact way to do these comments is by writing briefly about each variable or function, some variables are declared, while others are directly initialised and this is sufficient as a Doxygen comment.
