### ISSUE TITLE
The feedback changing so fast

### ISSUE THREAD

**Issue by Zi-han-Huang** [Mario-el-khoury/Smart-Intonation#11]
Recognizing the pitch of users voice, and give positive or negative feedback to the user(real-time). Now the feedback changing really fast and the user may not catch up with it.

**Comment by Mario-el-khoury** [comment]
The software is operating in real time and the feedback of the pitch is changing each 0.6 second, it is not logic to increase the delay of the feedback because this will generate a conflict between the feedback seen on the screen and the actual pitch of the user.
