### ISSUE TITLE
Changing the color of the piano key when the user sing the note.

### ISSUE THREAD

**Issue by Zi-han-Huang** [Mario-el-khoury/Smart-Intonation#12]
Some noise from the environment will also be recognized by the computer therefore the result should be filterd.

**Comment by Mario-el-khoury** [comment]
Filtering background noise can be done using a high-pass filter (HPF)  that passes signals with a frequency higher than a certain cut-off frequency and attenuates signals with frequencies lower than the cut-off frequency. In our case, we are dealing with a sound card, therefore in our code we have selected a range that we wish to work on, by doing so, we are taking into consideration a specific range of frequencies to study, therefore, it is the same as a Band pass filter that passes frequencies within a certain range and rejects (attenuates) frequencies outside that range. However, further filtering can be done to increase the accuracy of the software.
