### ISSUE TITLE
Fixed the problem of inaccurate frequency of notes

### ISSUE THREAD

**Issue by Jiangjiajun-Dominic** [Mario-el-khoury/Smart-Intonation#20]
We passed a test using a piano to correct the frequency of notes.

**Comment by Zi-han-Huang** [comment]
We passed a test using a piano to correct the frequency of notes, because the middle frequencies of MI and Ti are 262*pow(2, 4/12) and 262*pow(2, 11/12), which is different with whole tones like Do\Re\Mi ...
