### ISSUE TITLE
Constant value should add "static" or not?

### ISSUE THREAD

**Issue by Zi-han-Huang** [Mario-el-khoury/Smart-Intonation#7]
double sampleRate = 48000; 
int bufferTime = 600.0; 
double peakHertzScale =523.25;
double lowestFrequency = 100 ;
double highestFrequency = 1000;

Should change them into "static double/int ...." by adding a "static" before them in  order to keep them constant?

**Comment by Jiangjiajun-Dominic** [comment]
Yes! I have noticed that.I'm trying to make them be static to keep them safe and save the space.

**Comment by Jiangjiajun-Dominic** [comment]
OKay~ Made it.
